---
title: "Analyses_and_Plots"
author: "Austin Hammer"
date: "11/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r make_phyloseq_object, echo=FALSE}
library("readxl")
library("phyloseq")
library("ggplot2")
library("dplyr")
library("vegan")
library("DESeq2")
library("knitr")
library("OneR")
seqtab <- readRDS("C:/Users/hammera/Desktop/raber_550/data/290190_seqtab_final.rds")
seqtab.taxa <- readRDS("C:/Users/hammera/Desktop/raber_550/data/290190_taxa_final.rds")
seqtab <- (seqtab)
meta_data <- as.data.frame(read_excel("C:/Users/hammera/Desktop/raber_550/data/550_metadata_revised.xlsx"))
rownames(seqtab) <- meta_data$RaberSID
samples = sample_data(meta_data)
ASV = otu_table(seqtab, taxa_are_rows = FALSE)
TAX = tax_table(seqtab.taxa)
sample_names(samples) <- sample_names(ASV)
##Makes the phyloseq object and then subsets a couple of outlier samples
physeq = phyloseq(ASV, TAX, samples)
taxa_names(physeq) <- paste0("ASV", seq(ntaxa(physeq)))
physeq = subset_samples(physeq, sample_names(physeq) != ("93"))
physeq = subset_samples(physeq, sample_names(physeq) != "59")
physeq = subset_samples(physeq, sample_names(physeq) != "4") ## This sample is only subsetted because it is missing some covariate information
##Binning covariates that contain continuous covariates into quartiles for DESeq2 analysis downstream. This is recommended by DESeq2's author, for more information read the vignette
sample_data(physeq)$FSTTimeImmobile_binned <- bin(sample_data(physeq)$FSTTimeImmobile, nbins=4, labels=c("first", "second", "third", "fourth"), method="content")
sample_data(physeq)$NOObjpref_binned <- bin(sample_data(physeq)$NOObjpref, nbins=4, labels=c("first", "second", "third", "fourth"), method="content")
sample_data(physeq)$OFCentDur1_binned <- bin(sample_data(physeq)$OFCentDur1, nbins=4, labels=c("first", "second", "third", "fourth"), method="content")
sample_data(physeq)$FCCuedFrzTone_binned <- bin(sample_data(physeq)$FCCuedFrzTone, nbins=4, labels=c("first", "second", "third", "fourth"), method="content")
sample_data(physeq)$OFTotDistDay1_binned <- bin(sample_data(physeq)$OFTotDistDay1, nbins=4, labels=c("first", "second", "third", "fourth"), method="content")
sample_data(physeq)$PALatencyDiff_binned <- bin(sample_data(physeq)$PALatencyDiff, nbins=4, labels=c("first", "second", "third", "fourth"), method="content")
sample_data(physeq)$PALatCross_binned <- bin(sample_data(physeq)$PALatCross, nbins=4, labels=c("first", "second", "third", "fourth"), method="content")
sample_data(physeq)$Treatment <- factor(sample_data(physeq)$Treatment)
##Setting a couple of variables equal to physeq. Vars will be modified and updated later on
physeq1 <- physeq
phyloseq_object <- physeq
```

```{r alphadiv, echo=FALSE}
## While the p-value for ANOVA of alphadiv~Treatment isn't extremely low (Pr(>F)~0.13), Shannon~Treatment*Sex (Pr(>F)~0.06), Observed~Treatment (Pr(>F)~0.06) it might be useful to briefly mention this in light of Keaton's previous analysis which showed an increase in alphadiv associated with increased radiation exposure. However, this test also functions with the assumptions necessary for running ANOVA about which I am not certain.
## Should maybe look at mean #ofgenera observed as a function of radiation level. Considering the low count #s post-glom with phyloseq, is this going to be descriptive or meaningful
##Covariates = Sex+Treatment+FSTTimeImmobile+NOObjpref+OFCentDur1+FCCuedFrzTone+OFTotDistDay1
library("phyloseq")
some_sample_data <- data.frame(sample_data(physeq1))
sample_data(physeq1)$Alphadiv <- estimate_richness(physeq1, split=TRUE, measures=c("Shannon"))
corr_df <- data.frame(sample_data(physeq1))
aov_results <- aov(as.matrix(Alphadiv) ~ Treatment, data=corr_df)
anova_results <- anova(aov_results)
some_plot <- plot((as.matrix(Alphadiv))~FSTTimeImmobile, data=corr_df)
testing_cor_adiv <- cor.test(x=corr_df$FSTTimeImmobile, y=(as.matrix(corr_df$Alphadiv)), method=c("kendall"))
print(testing_cor_adiv)
```

```{r enfit, echo=FALSE}
## 
library("vegan")
treatment.env <- data.frame(sample_data(physeq1))
physeq1.rda <- rda(otu_table(physeq1)~Sex+Treatment+FSTTimeImmobile+NOObjpref+OFCentDur1+FCCuedFrzTone+OFTotDistDay1, data=treatment.env)
physeq1.enfit <- envfit(physeq1.rda~Sex+Treatment+FSTTimeImmobile+NOObjpref+OFCentDur1+FCCuedFrzTone+OFTotDistDay1, data=(treatment.env), perm=5000)
plot(physeq1.rda, type="t")
physeq_ordination <- decorana(data.frame(otu_table(physeq1)))
physeq_enfit <- envfit(physeq_ordination~Treatment*Sex+FSTTimeImmobile+NOObjpref+OFCentDur1+FCCuedFrzTone+OFTotDistDay1, data=treatment.env, perm=1000)
plot(physeq_ordination)
plot(physeq_enfit)
#plot(physeq1.enfit)
```

```{r bray_by_Sex_Treatment, echo=FALSE}
library("phyloseq")
physeq1.ord <- ordinate(physeq1, "NMDS", "bray")
sample_data(physeq1)$Treatment <- as.factor(sample_data(physeq1)$Treatment)
physeq1.ord.plot <- plot_ordination(physeq1, physeq1.ord, type="samples", color="Sex")
plot(physeq1.ord.plot)
physeq1.ord.treatment <- plot_ordination(physeq1, physeq1.ord, type="samples", color="Treatment", title="ByTreatment")
plot(physeq1.ord.treatment)
physeq1.ord.plot.treatment <- plot_ordination(physeq1, physeq1.ord, type="samples", color="Sex_Treatment", title="BySex_Treatment")##optional parameter for any of the above plots + stat_ellipse(level=0.95)
plot(physeq1.ord.plot.treatment)
```

```{r nmds_different_axes, echo=FALSE}
library(ggplot2)
set.seed(1)
physeq1 <- rarefy_even_depth(physeq1, rngseed=TRUE, verbose=FALSE)
physeq_nmds = metaMDS(otu_table(physeq1), distance="bray", k=4, trymax=1000, data=treatment.env)
nmds_table = scores(physeq_nmds, display="sites")
plot(nmds_table[,1], nmds_table[,3], main="Bray-Curtis Beta-div", xlab="NMDS1", ylab="NMDS3", pch=20, col=c("slateblue3", "tomato3", "darkolivegreen", "coral4"))
##This shows the ordination using different NMDS axes. These can be specified by performing metaMDS on the object otu_table and specifying k=(num of NMDS axes), then using the plot_ordination function with the phyloseq object, specifying colors and shapes based on metadata you want to visualize
physeq1.ord.plot <- plot_ordination(physeq1, physeq_nmds, type="samples", axes=c(1,3), color="Treatment", title="ByTreatment") ## + stat_ellipse(level=0.95)
print(physeq1.ord.plot)
physeq1 <- physeq

```

```{r adonis_results, echo=FALSE}
## Using adonis to evaluate the importance of covariates in explaining variation in the ordination produced using bray. Treatment*Sex has a large relative R2, and the Pr(>F) is quite low. 
library("phyloseq")
library("vegan")
set.seed(1)
physeq1 <- rarefy_even_depth(physeq1)
physeq1.dist <- vegdist(otu_table(physeq1), method="bray")
sampledf <- data.frame(sample_data(physeq1))
set.seed(1)
perm.results.treatment <- adonis(physeq1.dist ~ Treatment*Sex, data=sampledf, permutations=5000)
print(perm.results.treatment)
physeq1 <- physeq
```

```{r capscale_ordistep, echo=FALSE}
## We ran through possible permutations and options for model selection using AIC in ordistep after building a model in capscale. Results are available via mod. The best model found after running through covariate permutations was Treatment*Sex.
sampledf <- data.frame(sample_data(physeq))
physeq1.capsca <- capscale(physeq1.dist ~ Treatment*Sex, sampledf, dist="bray")
set.seed(1)
mod <- ordistep(physeq1.capsca, perm.max = 5000, trace = T, direction = "both")
print(mod)
```

```{r betadispersion, echo=FALSE}
## The graphical results of this suggest that there might be a difference in mean betadispersion, with particularly low dispersion among the highly radiated groups. Is lower betadispersion associated with higher radiation levels? Would that suggest that there are more relatively limited conformations adopted by the murine gut microbiome in association with radiation?
## Do I need to correct for multiple pairwise comparisons?
treatments <- factor(sample_data(physeq1)$Treatment)
betadispersion <- betadisper(physeq1.dist, treatments, type=c("centroid"))
boxplot(betadispersion)
set.seed(1)
testbetad <- permutest(betadispersion, pairwise=TRUE, permutations=5000)
print(testbetad)
beta_disp_tukey_result <- TukeyHSD(betadispersion, ordered=FALSE, conf.level=0.95)
```

```{r deseq2_function, echo=FALSE}
library("phyloseq")
taxa_with_deseq <- function(treatdds, physeq1){ 
  sigtab <- NULL
  ##treatdds = phyloseq_to_deseq2(phyloseq_object, ~"some_covariate")
  treatdds.deseq = DESeq(treatdds, fitType = "local", sfType = "poscounts")
  res = results(treatdds.deseq, cooksCutoff=FALSE)
  res = data.frame(res)
  alpha = 0.1
  ##Make a note of sfType -poscounts and fitType = local - This should decrease the likelihood that a single outlier drives the observation
  ## Behavioral results are probably being driven by this,
  ##prevalence filter 
  res2   <- subset(res, !is.na(res$padj))
  sigtab <- subset(res2, res2$padj < alpha)
  if (nrow(sigtab)>0){
    sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(physeq1)[rownames(sigtab), ], "matrix"))
    return(sigtab)
  } else {
    return("No significant taxa were identified using the specified formula")
  }
}

```

```{r ASV_analysis, echo=FALSE}
## This first step agglomerates to a chosen level, then you can use the workthrough below to continue the analysis
## Covariates = Sex+Treatment+FSTTimeImmobile+NOObjpref+OFCentDur1+FCCuedFrzTone+OFTotDistDay1
library(DESeq2)
set.seed(1)
physeq1<-physeq
phyloseq_object <- physeq1
physeq_genus <- tax_glom(physeq, taxrank="Genus")
##This is a basic workthrough that runs DESeq2 for analysis of taxa analysis. One thing that that I should consider is filtering the available taxa to so that only taxa that are present in 50% of samples or greater. This would eliminate this issue where differences are inflated by the presence of a bunch of zeros for a particular group. I think that effect could largely be driven by the Box covariate, which is possibly suggested in the adonis results as well.
## A couple limitations 
sigtab <- NULL
treatdds = phyloseq_to_deseq2(physeq_genus, ~Treatment)
treatdds.deseq = DESeq(treatdds)
res = results(treatdds.deseq, cooksCutoff=FALSE)
res = data.frame(res)
alpha = 0.1
remove_nas <- is.na(res$adj)
sigtab <- subset(res, remove_nas)
res <- subset(res, !is.na(res$padj))
sigtab <- subset(res, res$padj < alpha)
if (nrow(sigtab)>0){
  sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(physeq1)[rownames(sigtab), ], "matrix"))
  print(sigtab)
  } else {
    print("No significant taxa were identified using the specified formula")
  }

## Generate a couple of sigtab tables that reflect significant taxa according to behavioral covariates and permutations of Treatment/Sex. Does Treatment*Sex include Treatment, Sex, and Treatment*Sex taxa? perform at each level and see
## After generating the taxa tables, see which taxa might be common between sets
## Get a feel for the taxa present by looking at microbes observed in Keaton's work, and what might have been observed elsewhere 

asv_table=(otu_table(phyloseq_object))
sample_data_to_smash=sample_data(phyloseq_object)
taxa_table_plus_metadata_asv <- data.frame(cbind(data.frame(asv_table), data.frame(sample_data_to_smash)))
asv_table_rare <- rarefy_even_depth(otu_table(phyloseq_object))
taxa_table_plus_metadata_asv_rare <- data.frame(cbind(data.frame(asv_table_rare), data.frame(sample_data_to_smash)))

genus_table=(otu_table(physeq_genus))
sample_data_to_smash_genus=sample_data(physeq_genus)
taxa_table_plus_metadata_genus <- data.frame(cbind(data.frame(genus_table), data.frame(sample_data_to_smash_genus)))
physeq_genus_rare <- rarefy_even_depth(physeq_genus)
genus_table_rare <- otu_table(physeq_genus_rare)
taxa_table_plus_metadata_genus_rare <- data.frame(cbind(data.frame(genus_table_rare), data.frame(sample_data_to_smash_genus)))

```

```{r filter_taxa_chunk, echo=FALSE}
## this is an optional chunk of code to run if you want to filter taxa for only those that are reasonably abundant. In the case below taxa that show up more than three times in more than 10% of samples will be filtered
## Run the chunks above to set to the default settings using a variety of 
physeq1_filt = filter_taxa(physeq, function(x) sum(x > 3) > (0.1*length(x)), TRUE)
phyloseq_object <- physeq1_filt
physeq_genus <- tax_glom(physeq, taxrank="Genus")

```

```{r ASV_by_OFTotDistDay1, echo=FALSE}
## DESeq2 analysis using the specified covariate (ASV level)
treatdds = phyloseq_to_deseq2(phyloseq_object, ~OFTotDistDay1)
## Generated table containing ASVs
OFTotDistDay1_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(OFTotDistDay1_ASVs)
## DESeq2 genus level analysis using OFTotDistDay1
treatdds = phyloseq_to_deseq2(physeq_genus, ~OFTotDistDay1)
## Genus level table
OFTotDistDay1_genus <- taxa_with_deseq(treatdds, physeq_genus)
print(OFTotDistDay1_genus)
```

```{r ASV_by_FSTTimeImmobile, echo=FALSE}
## DESeq2 analysis using the specified covariate (ASV level)
treatdds = phyloseq_to_deseq2(phyloseq_object, ~FSTTimeImmobile)
## Generated table containing ASVs
FSTTimeImmobile_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(FSTTimeImmobile_ASVs)
## DESeq2 genus level analysis using FSTTimeImmobile
treatdds = phyloseq_to_deseq2(physeq_genus, ~FSTTimeImmobile)
## Genus level table
FSTTimeImmobile_genus <- taxa_with_deseq(treatdds, physeq_genus)
print(FSTTimeImmobile_genus)
```

```{r ASV_by_NOObjpref, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~NOObjpref)
## Generated table containing ASVs
NOObjpref_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(NOObjpref_ASVs)
## DESeq2 analysis using NOObjpref
treatdds = phyloseq_to_deseq2(physeq_genus, ~NOObjpref)
## Genus level table
NOObjpref_genus <- taxa_with_deseq(treatdds, physeq_genus)
print(NOObjpref_genus)

```

```{r ASV_by_OFCentDur1, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~OFCentDur1)
## Generated table containing ASVs
OFCentDur1_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(OFCentDur1_ASVs)
## DESeq2 analysis using OFCentDur1
treatdds = phyloseq_to_deseq2(physeq_genus, ~OFCentDur1)
## Genus level table
OFCentDur1_genus <- taxa_with_deseq(treatdds, physeq_genus)
print(OFCentDur1_genus)
```

```{r ASV_by_Treatment, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~Treatment)
## Generated table containing ASVs
Treatment_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(Treatment_ASVs)
## DESeq2 analysis using Treatment
treatdds = phyloseq_to_deseq2(physeq_genus, ~Treatment)
## Genus level table
Treatment_genus <- taxa_with_deseq(treatdds, physeq_genus)
print(Treatment_genus)
## ASV656 identified as significant using DESeq2 at the genus level, occurs more frequently and in increased abundance across samples at radiation levels under 50cGy, but its abundance and presence is markedly lower at 200cGy (p-value ~0.02)
##plotting_taxa <- ggplot(taxa_table_plus_metadata_genus_rare, aes(x=(Treatment), y=ASV656))  + geom_smooth() + geom_jitter()
##plotting_taxa

##plotting_taxa <- ggplot(taxa_table_plus_metadata_asv_rare, aes(x=Treatment, y=ASV231))  + geom_point(aes(color=Treatment))
##plotting_taxa
##ASVs: 231 (Rikenellaceae - Alstipes), 
```

```{r ASV_by_Sex, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~Sex)
## Generated table containing ASVs
Sex_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(Sex_ASVs)
## DESeq2 analysis using Sex
treatdds = phyloseq_to_deseq2(physeq_genus, ~Sex)
## Genus level table
Sex_genus <- taxa_with_deseq(treatdds, physeq_genus)
print(Sex_genus)
```

```{r ASV_by_Treatment_interaction_Sex, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~Sex*Treatment)
## Generated table containing ASVs
Treatment_Sex_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(Treatment_Sex_ASVs)
## DESeq2 analysis using Treatment*Sex
treatdds = phyloseq_to_deseq2(physeq_genus, ~Sex*Treatment)
## Genus level table
Treatment_Sex_genus <- taxa_with_deseq(treatdds, physeq_genus)

##plotting_taxa <- ggplot(taxa_table_plus_metadata_asv_rare, aes(x=Treatment, y=ASV191))  + geom_point(aes(color=Treatment)) + facet_grid(row=vars(Sex)) + geom_boxplot()
##plotting_taxa

print(Treatment_Sex_genus)
```

```{r ASV_by_FSTTimeImmobile_binned, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~FSTTimeImmobile_binned)
## Generated table containing ASVs
FSTTimeImmobile_binned_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(FSTTimeImmobile_binned_ASVs)
## DESeq2 analysis using FSTTimeImmobile_binned
treatdds = phyloseq_to_deseq2(physeq_genus, ~FSTTimeImmobile_binned)
## Genus level table
FSTTimeImmobile_binned_genus <- taxa_with_deseq(treatdds, physeq_genus)

print(FSTTimeImmobile_binned_genus)
#ASVs of interest: 315, 335, 336, 407, 513
plotting_taxa <- ggplot(taxa_table_plus_metadata_asv_rare, aes(x=FSTTimeImmobile_binned, y=ASV264))  + geom_boxplot() + geom_jitter()
plotting_taxa
```

```{r ASV_by_NOObjpref_binned, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~NOObjpref_binned)
## Generated table containing ASVs
NOObjpref_binned_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(NOObjpref_binned_ASVs)
## DESeq2 analysis using FSTTimeImmobile_binned
treatdds = phyloseq_to_deseq2(physeq_genus, ~NOObjpref_binned)
## Genus level table
NOObjpref_binned_genus <- taxa_with_deseq(treatdds, physeq_genus)

print(NOObjpref_binned_genus)
#ASVs: 308, 323, 325, 336, 369, 374, 417, 
## With some covariates the scores are reasonably close to each other, which could result in a very small difference between groups 1, 2, and 3, whereas the 4 group is way out. Additionally, the issue of sparsity makes it hard to determine if a particular trend is driven by a specific ASV or is just a stochastic artifact.
## Wouldn't sparsity make correlation pretty difficult to determine with most microbiome data? At least at the level of ASV vs some covariate?
```

```{r ASV_by_OFCentDur1_binned, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~OFCentDur1_binned)
## Generated table containing ASVs
OFCentDur1_binned_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(OFCentDur1_binned_ASVs)
## DESeq2 analysis using FSTTimeImmobile_binned
treatdds = phyloseq_to_deseq2(physeq_genus, ~OFCentDur1_binned)
## Genus level table
OFCentDur1_binned_genus <- taxa_with_deseq(treatdds, physeq_genus)

print(OFCentDur1_binned_genus)
##ASVs: 336, 370, 463,  (look at binned and not binned), 
```

```{r ASV_by_OFTotDistDay1_binned, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~OFTotDistDay1_binned)
## Generated table containing ASVs
OFTotDistDay1_binned_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(OFTotDistDay1_binned_ASVs)
## DESeq2 analysis using FSTTimeImmobile_binned
treatdds = phyloseq_to_deseq2(physeq_genus, ~OFTotDistDay1_binned)
## Genus level table
OFTotDistDay1_binned_genus <- taxa_with_deseq(treatdds, physeq_genus)

print(OFTotDistDay1_binned_genu)
##ASVs: 316 (consider binned vs non),
##One pattern that could emerge is that simply having a higher bacterial load might be associated with higher scores on some behavioral assays, perhaps this is independent of a particular taxa and has to do with immune function related to taxa
## I would be interested to see if there are any taxa that covary with measured BDNF levels, as that might be an interesting possible mechanistic focus
```

```{r ASV_by_PALatencyDiff_binned, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~PALatencyDiff_binned)
## Generated table containing ASVs
PALatencyDiff_binned_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(PALatencyDiff_binned_ASVs)
## DESeq2 analysis using FSTTimeImmobile_binned
treatdds = phyloseq_to_deseq2(physeq_genus, ~PALatencyDiff_binned)
## Genus level table
PALatencyDiff_binned_genus <- taxa_with_deseq(treatdds, physeq_genus)

print(PALatencyDiff_binned_genus)
##ASVs: 

##plotting_taxa <- ggplot(taxa_table_plus_metadata_asv_rare, aes(x=PALatencyDiff, y=ASV302))  + geom_point(aes(color=Sex))
##plotting_taxa
```

```{r ASV_by_PALatCross_binned, echo=FALSE}
## Convert to deseq2 object using the specified covariate
treatdds = phyloseq_to_deseq2(phyloseq_object, ~PALatCross_binned)
## Generated table containing ASVs
PALatCross_binned_ASVs <- taxa_with_deseq(treatdds, physeq1)
print(PALatCross_binned_ASVs)
## DESeq2 analysis using FSTTimeImmobile_binned
treatdds = phyloseq_to_deseq2(physeq_genus, ~PALatCross_binned)
## Genus level table
PALatCross_binned_genus <- taxa_with_deseq(treatdds, physeq_genus)

print(PALatCross_binned_genus)

##ASVs: 
```

```{r commentary}
##Alpha diversity is a metric that describes the diversity of taxa in a specific sample or set. Alpha diversity measures did not differ significantly between treatment groups, and no association between alpha diversity and radiation level was detected. However, FSTTimeImmobile times were associated with alpha diversity (alpha diversity metric "Shannon", Kendall's tau, p-value=0.03692).
##Beta diversity is an estimate of diversity between different samples. Beta diversity was first estimated using the Bray-Curtis dissimilarity index, and a NMDS ordination was created. From this information, an analog to step-wise AIC was used to elucidate the best model for predicting differences in beta-diversity. PERMANOVA was performed using Treatment x Sex to quantify the difference in beta diversity between samples. The results of this test suggest that the composition of the gut changes in response to Treatment interacting with Sex (p-value ~0.0006, R2~0.041). No other covariates significantly associated with beta diversity.
##There were associations between covariates of interest and taxa. DESeq2 was used to analyze the association between bacterial taxa and several covariates at the genus and species (ASV) level. The abundance of some taxa associated with the level of radiation exposure as a function of host sex. This was observed for the Bacteroides and Turicibacter genera, where an increased abundance was associated with higher radiation exposure in female mice but not in male mice. An increase in the both genera has previously been observed in radiation-induced gut dysbiosis and inflammation (https://gut.bmj.com/content/67/1/97).



## Of note, fewer taxa were shown to be significant after changing the parameters above
```

```{r merging_physeq_objects}
##You need to remove the tree from physeq_s1 because it messes up the merging of physeq objects
set.seed(1)
physeq_s1 <- readRDS("C:/Users/hammera/Desktop/raber_550/data/three-beam_physeq.rds")
sample_data(physeq_s1)$Treatment <- factor(sample_data(physeq_s1_genus)$Radiation.Conc.cGy)
sample_data(physeq_s1)$Study <- "Three-beam"
sample_data(physeq)$Study <- "Six-beam"
oldstudytax <- tax_table(physeq_s1)
oldstudyasv <- otu_table(physeq_s1)
oldstudydata <- sample_data(physeq_s1)
new_physeq_s1 <- phyloseq(oldstudytax, oldstudyasv, oldstudydata)
new_merged_physeq <- merge_phyloseq(new_physeq_s1, (physeq))
##new_merged_physeq <- subset_samples(new_merged_physeq, Treatment=="0")
new_merged_physeq <- tax_glom(new_merged_physeq, "Genus")
new_merged_physeq <- rarefy_even_depth(new_merged_physeq)
merged_df <- data.frame(sample_data(new_merged_physeq)[,1:3])
sample_data(new_merged_physeq) <- sample_data(merged_df)
new_physeq_ordination_merged <- ordinate(new_merged_physeq, method="NMDS", distance="jaccard")
plot_new_merged_ordination <- plot_ordination(new_merged_physeq, new_physeq_ordination_merged, type="samples", color="Treatment", shape="Study")
plot_new_merged_ordination
##merged_ordination = metaMDS(otu_table(new_merged_physeq), distance="bray", k=4, trymax=1000, data=merged_df)
##nmds_table = scores(merged_ordination, display="sites")
##plot(nmds_table[,1], nmds_table[,2], main="Bray-Curtis Beta-div", xlab="NMDS1", ylab="NMDS2", pch=20, shape="Study")


##PERMANOVA to show that the difference is actually frigging huge
study_object_dist <- vegdist(otu_table(new_merged_physeq), "bray")
set.seed(1)
study_difference_permanova <- adonis(study_object_dist ~ Study, data=merged_df, permutations=5000)
print(study_difference_permanova)
```



































